export type Locale = "en" | "ru";

// Контакты студии; почта и домен подъедут следом.
export const contacts = {
  tg: "https://t.me/g3n1sss",
  email: "", // TODO: почта студии
};

export const dict = {
  en: {
    meta: {
      title: "ARIYA — digital product studio",
      description:
        "Apps, Telegram Mini Apps and websites that make money — not just exist.",
    },
    brand: "ARIYA",
    nav: [
      { label: "Services", href: "#services" },
      { label: "Work", href: "#work" },
      { label: "Process", href: "#process" },
      { label: "Contact", href: "#contact" },
    ],
    headerCta: "Message us",
    themeToggle: "Dark / light theme",
    localeSwitch: { label: "RU", href: "/" },
    greet: {
      morning: "good morning — coffee, brief, estimate in 1–2 days",
      day: "good afternoon — we can scope your task by tonight",
      evening: "good evening — prime time for bold ideas",
      night: "can’t sleep? the form works around the clock",
      habr: "hi, habr — our code is cleaner than our articles",
      tg: "from telegram? that’s where we live",
    },
    hero: {
      eyebrow: "Digital product studio",
      h1: ["Your product.", "Our performance."],
      sub: "We build apps, Telegram Mini Apps and websites that make money — not just exist. Three people, working worldwide, and you always talk to whoever writes the code.",
      ctaPrimary: "Tell us about your project",
      ctaSecondary: "See our work",
      ticker: "apps /// mini apps /// websites /// worldwide",
    },
    services: {
      idx: "// 01",
      title: "What we do",
      intro: "Three tracks, one bar: the product has to pay off.",
      items: [
        {
          name: "Mobile apps",
          text: "iOS and Android end to end: idea, design, store release, support. Built to live and grow — not die after launch.",
        },
        {
          name: "Telegram Mini Apps",
          text: "Sell where your customers already are. Stores, bookings, loyalty and internal tools right inside Telegram — no install needed. Weeks to launch, not months.",
        },
        {
          name: "Websites",
          text: "Fast, modern, impossible to mistake for a template. Want proof? You’re looking at it.",
        },
      ],
      plus: "+ bots, AI integrations, automation. If it’s digital — bring it over.",
      demo: {
        tg: {
          title: "ariya · mini app",
          hello: "a store right inside Telegram — nothing to install",
          btnCatalog: "catalog",
          btnPay: "checkout",
          catalogReply: "storefront, cart, search — all in the chat",
          payReply: "payments built in: cards, stars, crypto",
          paid: "✓ paid",
          reset: "once more",
        },
        web: {
          hint: "hover — see how it’s built",
          labels: ["nav / sticky", "hero / clamp()", "card / --radius", "grid 12"],
        },
      },
    },
    cases: {
      idx: "// 02",
      title: "Work",
      intro: "Talk is cheap. Here’s what we’ve shipped:",
      items: [
        {
          id: "novy-uroven",
          tag: "case-01",
          client: "T2 · web game (PWA)",
          title: "Novy Uroven",
          text: "An endless climber for telecom brand T2: a signal-character hops up cell towers through the network eras — 2G to 6G. Lives in the browser as a PWA: WebGL rendering, offline play, cloud leaderboard.",
          stack: ["React", "TypeScript", "PixiJS · WebGL", "PWA", "Neon"],
          link: "https://novi-uroven.vercel.app",
          linkLabel: "play it",
          pageHref: "/en/work/novy-uroven",
          pageLabel: "case study \u2192",
          img: "/cases/novy-uroven.png",
          alt: "Novy Uroven gameplay: the signal character jumps across cell towers",
          // лента эпох на постере: прогрессия сетей как мини-история
          strip: [
            {
              img: "/cases/novy-uroven-3g.png",
              cap: "3G",
              alt: "Novy Uroven: the 3G era, low towers over the city",
            },
            {
              img: "/cases/novy-uroven.png",
              cap: "gameplay",
              alt: "Novy Uroven gameplay: the signal character jumps across cell towers",
            },
            {
              img: "/cases/novy-uroven-6g.png",
              cap: "6G · finale",
              alt: "Novy Uroven: the 6G era, the future banner in orbit",
            },
          ],
        },
        {
          id: "novy-kovcheg",
          tag: "case-02",
          client: "Novy Kovcheg · banquet house",
          title: "Novy Kovcheg",
          text: "The full digital storefront for a banquet house in Kimovsk. Stage one is live: four halls, three menus and a booking form in one warm serif journey. Stage two — a banquet delivery e-shop — is in the works.",
          stack: ["Astro 5", "TypeScript", "GSAP", "Lenis"],
          link: "https://noviykovcheg.ru",
          linkLabel: "visit site",
          pageHref: "/en/work/novy-kovcheg",
          pageLabel: "case study \u2192",
          img: "/cases/novy-kovcheg.png",
          alt: "Novy Kovcheg landing: dark hero with a chandelier and serif wordmark",
          strip: [
            {
              img: "/cases/novy-kovcheg.png",
              cap: "entrance",
              alt: "Novy Kovcheg hero: dark velvet, chandelier, serif title",
            },
            {
              img: "/cases/novy-kovcheg-hall.png",
              cap: "the Grand hall",
              alt: "Grand hall page with a live banquet photo",
            },
            {
              img: "/cases/novy-kovcheg-menu.png",
              cap: "three menus",
              alt: "Menu packages with honest per-guest pricing",
            },
          ],
        },
      ],
      placeholderTitle: "Open slot",
      placeholderNote: "The next case could be your project — message us.",
      stampSoon: "soon",
      closing:
        "Want the same breakdown for your idea? Message us — we’ll show you what’s possible.",
    },
    why: {
      idx: "// 03",
      title: "Why ARIYA",
      lead: "Big studios sell process: managers, meetings, status decks. We sell outcomes. Three of us — each personally on the hook for the result.",
      bullets: [
        {
          name: "No broken telephone.",
          text: "Direct line to those who design and code.",
        },
        {
          name: "Small-team speed.",
          text: "Decisions in minutes, first results in days.",
        },
        {
          name: "A 2026 stack.",
          text: "The same tools behind the best products out there — including this site.",
        },
        {
          name: "Worldwide.",
          text: "Any timezone, English and Russian.",
        },
      ],
    },
    process: {
      idx: "// 04",
      title: "How it works",
      steps: [
        {
          name: "Talk",
          text: "A call or a chat — your pick. We dig into the task and tell you honestly what will fly and what won’t.",
        },
        {
          name: "Estimate",
          text: "An honest price range and timeline — fast and without surprises.",
        },
        {
          name: "Build",
          text: "Short iterations, weekly demos, no month-long silence.",
        },
        {
          name: "Launch & beyond",
          text: "Release, metrics, support. We don’t vanish after launch.",
        },
      ],
    },
    cta: {
      idx: "// 05",
      title: "Tell us what you want to build.",
      sub: "Telegram is fastest. Two sentences about the task — we’ll ask the rest.",
      ticker: "available for projects /// 2026 /// worldwide",
      pricing:
        "No “$X and up” price lists — they lie anyway. We look at the task and give you an honest range.",
      btnTg: "Message on Telegram",
      btnMail: "Email us",
      form: {
        hint: "// or assemble the brief right here — we’ll reply wherever suits you",
        name: "Name",
        contact: "Telegram or email",
        about: "Anything in your own words (optional)",
        send: "Send",
        sending: "Sending…",
        ok: "Got it. We’ll be in touch soon.",
        fail: "Didn’t go through. Telegram is the reliable way.",
        off: "The form wakes up with our contacts — Telegram is faster for now.",
        what: "what we’re building",
        feats: "what’s inside",
        stage: "where you are",
        products: ["mobile app", "tg mini app", "website", "bot"],
        features: ["auth", "payments", "admin panel", "push", "ai", "3d"],
        stages: ["just an idea", "have designs", "rebuild existing"],
        previewTitle: "new request",
        pProduct: "product",
        pFeats: "inside",
        pStage: "stage",
        pName: "name",
        pContact: "contact",
      },
    },
    footer: {
      brand: "ARIYA — digital product studio",
      rights: "© 2026",
      logLink: "// changelog",
      logHref: "/en/changelog",
    },
    changelog: {
      title: "Changelog",
      lead: "We run this site like a product: releases, dates, honest history.",
      back: "← back to site",
      backHref: "/en",
      releases: [
        {
          v: "1.6",
          date: "22.08.2026",
          items: [
            "case 01 \u00ab\u041dovy Uroven\u00bb: game-styled page \u2014 night sky, neon, 3D tower diorama",
            "case 02 \u00abNovy Kovcheg\u00bb: velvet entrance, chandelier, crystal Prisma on a chain",
            "era-strip posters on the home page, roadmap of client stages",
            "lead form plumbing + analytics goals \u2014 wake up with the domain",
          ],
        },
        {
          v: "1.5",
          date: "18.08.2026",
          items: [
            "dark theme — inky night: tokens, neon buttons, moonlit 3D",
            "theme toggle in the header + \u2318K command, choice remembered",
          ],
        },
        {
          v: "1.4",
          date: "17.08.2026",
          items: [
            "⌘K command palette",
            "Prisma the mascot moved in as a site guide",
            "brief builder with live telegram preview",
            "live demos inside service cards",
            "particle echo of the mark in the hero",
            "living hero typography, context greetings",
            "page-morph transitions, open metrics + this page",
          ],
        },
        {
          v: "1.3",
          date: "17.08.2026",
          items: [
            "lead form → telegram, SEO, custom 404 with Prisma",
            "Prisma got real 3D and an emotion system",
          ],
        },
        {
          v: "1.2",
          date: "16.08.2026",
          items: [
            "3D logo flies zigzag between scenes",
            "dolly-zoom parking into the footer wordmark",
          ],
        },
        {
          v: "1.1",
          date: "16.08.2026",
          items: [
            "preloader assembles the mark on every visit",
            "custom cursor, tickers, section art",
          ],
        },
        {
          v: "1.0",
          date: "15.08.2026",
          items: ["skeleton, design system, RU/EN, copy"],
        },
      ],
    },
    casePage: {
      back: "\u2190 all work",
      backHref: "/en#work",
      tag: "// case-01",
      client: "T2 \u00b7 web game (PWA)",
      title: "Novy Uroven",
      lead: "A web game for mobile operator T2 \u2014 an endless vertical climber. The signal character jumps up cell towers from the 2G era into the future, collecting gigabytes on the way. Opens from a link, and after the first visit works with no connection at all \u2014 \u201ca telecom made a game that works without telecom\u201d.",
      play: "play it \u2197",
      link: "https://novi-uroven.vercel.app",
      shots: [
        { img: "/cases/novy-uroven-menu.png", cap: "menu \u2014 any frame reads as T2" },
        { img: "/cases/novy-uroven.png", cap: "gameplay: towers, wires, a new record" },
        { img: "/cases/novy-uroven-over.png", cap: "game over \u2014 \u201cStuck on 2G. That hurts\u201d" },
      ],
      taskH: "The task",
      taskText: "T2 needed a daily reason for subscribers to come back: engagement on the gaming segment, product education through boosters named after real services, and virality through a leaderboard and record sharing. The format \u2014 a casual 3\u201310 minute game for the commute: no install, no network required.",
      builtH: "What\u2019s inside",
      built: [
        "Jump core on tuned physics: auto-jump, one-way platforms, horizontal wrap \u2014 game feel dialed in on real devices",
        "Fair procedural generation: every level is passable, you only die by your own fault \u2014 a validator proves it in tests",
        "Three control schemes \u2014 tilt, swipe, tap zones \u2014 so it plays even on a shaky bus",
        "Network eras 2G\u21926G as progression: the world and palette change as you climb",
        "PWA with full offline: Workbox cache, progress in IndexedDB, instant restart",
        "Cloud leaderboard on serverless Postgres (Neon) + record sharing",
      ],
      flowH: "How the work went",
      flow: [
        { n: "01", name: "Foundation", text: "Vite + React + TypeScript strict, PixiJS renderer, Vercel auto-deploy from day one." },
        { n: "02", name: "Jump core", text: "Gravity, platforms, camera, pooled generation \u2014 and a physics tuning loop on a real phone." },
        { n: "03", name: "Gameplay depth", text: "Boosters named after the product line, crystals, era progression, reward economy." },
        { n: "04", name: "Iterations", text: "Production is open from the first stage \u2014 every feature ships with a push. You can play right now." },
      ],
      erasH: "Network eras \u2014 higher is faster",
      erasNote: "The world, palette and banners change as you climb: 2G \u2192 3G \u2192 LTE \u2192 5G \u2192 6G. Captured live from the game:",
      eras: [
        { img: "/cases/novy-uroven-3g.png", cap: "3G \u00b7 \u201cUzhe chto-to\u201d \u2014 getting somewhere" },
        { img: "/cases/novy-uroven-lte.png", cap: "LTE \u00b7 time to speed up" },
        { img: "/cases/novy-uroven-5g.png", cap: "5G \u00b7 almost space" },
        { img: "/cases/novy-uroven-6g.png", cap: "6G \u00b7 \u201cThe future. You\u2019re first here\u201d" },
      ],
      stackH: "Stack",
      stack: ["React 18", "TypeScript strict", "Vite", "PixiJS 8 \u00b7 WebGL", "Zustand", "PWA \u00b7 Workbox", "IndexedDB", "Neon"],
      ctaH: "Want a product people actually play?",
      ctaBtn: "discuss on Telegram",
      strip: {
        cap: "// the game world: from a 2G pole to the 6G spire",
        hint: "scroll tilts it \u00b7 cursor sways it \u00b7 click the jumper",
        eras: ["2G", "3G", "LTE", "5G", "6G"],
      },
      decor: {
        vign1: "// idea \u2192 product",
        vign2: "// 4 sprints",
      },
    },
    guide: {
      hello: "hey! I live here. click me — or press ⌘K",
      services: "everything here is buyable — and it actually runs",
      work: "two live cases already — open any, it's all real",
      process: "estimate in 1–2 days. I keep an eye on these three",
      contact: "two sentences is enough — the form flies straight to our telegram",
      sent: "got it! the team is already reading. I checked",
    },
    casePageNk: {
      back: "\u2190 all work",
      backHref: "/en#work",
      tag: "// case-02",
      client: "Novy Kovcheg \u00b7 banquet house, Kimovsk",
      title: "Novy Kovcheg",
      lead: "We are building the venue's whole digital presence. Stage one \u2014 a warm serif landing that sells the atmosphere of four halls and brings bookings straight to the owner's Telegram. Stage two, a banquet delivery e-shop, is already in the works on the same design system.",
      play: "visit the site",
      link: "https://noviykovcheg.ru",
      shots: [
        { img: "/cases/novy-kovcheg.png", cap: "entrance \u2014 dark velvet and a chandelier" },
        { img: "/cases/novy-kovcheg-hall.png", cap: "the Grand hall with live banquet photos" },
        { img: "/cases/novy-kovcheg-menu.png", cap: "three menus \u2014 honest price per guest" },
      ],
      taskH: "The task",
      taskText: "The venue had a site from another decade: heavy, desktop-only, with outdated numbers. Guests choose a hall with their eyes \u2014 so the site had to feel like the place itself: warm, festive, precise. And every page had to lead to one action \u2014 booking a date.",
      builtH: "What's inside",
      built: [
        "A design system from scratch: Playfair + Onest, ink / cream / champagne, photo frames with a gold inner line",
        "Four halls as scenes \u2014 from the grand chandeliers to the VIP room, each with its own art direction",
        "Three menu packages with real prices and a separate full menu page",
        "A booking form without a heavy backend: the lead flies to the owner's Telegram, with e-mail fallback",
        "Astro static output: zero framework JS at runtime, instant load on guests' phones",
        "SEO foundation: EventVenue + FAQ schema, sitemap, consistent contact data",
      ],
      flowH: "How it went",
      flow: [
        { n: "01", name: "Master brief", text: "Goals, structure and stage-by-stage plan with definitions of done \u2014 agreed before any pixels." },
        { n: "02", name: "Design system", text: "Palette, serif typography and per-section art direction \u2014 approved as a written brief." },
        { n: "03", name: "Sections & motion", text: "Layout from scratch, GSAP reveals, Lenis scroll \u2014 calm, festive choreography." },
        { n: "04", name: "Content & launch", text: "Photo processing, copy, schema markup, deploy package for plain hosting." },
      ],
      moreH: "More of the journey",
      more: [
        { img: "/cases/novy-kovcheg-halls.png", cap: "four halls for any scale" },
        { img: "/cases/novy-kovcheg-demo.png", cap: "the owner shows all four halls in person" },
        { img: "/cases/novy-kovcheg-form.png", cap: "contacts \u2014 phones, Telegram, VK" },
      ],
      stackH: "Stack",
      stack: ["Astro 5", "TypeScript", "GSAP", "Lenis", "Sharp", "PHP \u2192 Telegram"],
      ctaH: "Want a site that sells the atmosphere?",
      ctaBtn: "discuss in Telegram",
      ch: "chapter",
      stagesH: "Roadmap",
      stages: [
        {
          st: "stage 01 \u00b7 live",
          live: true,
          name: "Landing with booking",
          text: "Four halls, menus, FAQ and a lead form \u2014 the venue's digital front door.",
        },
        {
          st: "stage 02 \u00b7 in the works",
          live: false,
          name: "Delivery e-shop",
          text: "Banquet dishes to order online \u2014 same design system, one seamless brand.",
        },
      ],
    },
    ck: {
      aria: "Command palette",
      placeholder: "type a command or search…",
      empty: "// nothing — try different words",
      items: [
        { id: "services", label: "Go to: services", hint: "// 01" },
        { id: "work", label: "Go to: work", hint: "// 02" },
        { id: "process", label: "Go to: process", hint: "// 04" },
        { id: "contact", label: "Go to: contact", hint: "// 05" },
        { id: "lead", label: "Leave a request", hint: "form → telegram" },
        { id: "lang", label: "Переключить на русский", hint: "/" },
        { id: "prisma", label: "Call Prisma", hint: "mascot" },
        { id: "changelog", label: "Changelog", hint: "/en/changelog" },
        { id: "theme", label: "Toggle theme", hint: "dark / light" },
      ],
    },
    nf: {
      title: "Wrong click.",
      text: "This page doesn’t exist. Prisma is already out looking for it — meanwhile, head back home.",
      cta: "Back home",
      note: "// prisma is on it",
    },
  },
  ru: {
    meta: {
      title: "АРИЯ — студия цифровых продуктов",
      description:
        "Приложения, Telegram-миниаппы и сайты, которые зарабатывают, а не просто существуют.",
    },
    brand: "АРИЯ",
    nav: [
      { label: "Услуги", href: "#services" },
      { label: "Работы", href: "#work" },
      { label: "Процесс", href: "#process" },
      { label: "Контакт", href: "#contact" },
    ],
    headerCta: "Написать",
    themeToggle: "Тёмная / светлая тема",
    localeSwitch: { label: "EN", href: "/en" },
    greet: {
      morning: "доброе утро — кофе, бриф, оценка за 1–2 дня",
      day: "добрый день — успеем обсудить задачу до вечера",
      evening: "добрый вечер — самое время смелых идей",
      night: "не спится? форма работает круглосуточно",
      habr: "привет, хабр — код у нас чище статей",
      tg: "из телеграма? там и живём",
    },
    hero: {
      eyebrow: "Студия цифровых продуктов",
      h1: ["Ваш продукт.", "Наше исполнение."],
      sub: "Делаем приложения, Telegram-миниаппы и сайты, которые зарабатывают, а не просто существуют. Нас трое, работаем по всему миру — и вы всегда говорите с тем, кто пишет код.",
      ctaPrimary: "Обсудить задачу",
      ctaSecondary: "Смотреть работы",
      ticker: "приложения /// мини-аппы /// сайты /// worldwide",
    },
    services: {
      idx: "// 01",
      title: "Что делаем",
      intro: "Три направления, одна планка: продукт должен окупаться.",
      items: [
        {
          name: "Мобильные приложения",
          text: "iOS и Android под ключ: идея, дизайн, публикация в сторах, поддержка. Делаем так, чтобы приложение жило и росло, а не умерло после релиза.",
        },
        {
          name: "Telegram Mini Apps",
          text: "Продавайте там, где клиент уже сидит. Магазины, записи, лояльность, внутренние инструменты — прямо в Telegram, без установки. Запуск за недели, а не месяцы.",
        },
        {
          name: "Сайты",
          text: "Быстрые, современные, с дизайном, который не спутать с шаблоном. Хотите пример? Вы на нём.",
        },
      ],
      plus: "+ боты, ИИ-интеграции, автоматизация. Если задача цифровая — приносите, разберёмся.",
      demo: {
        tg: {
          title: "ariya · mini app",
          hello: "магазин прямо в Telegram — ничего не устанавливая",
          btnCatalog: "каталог",
          btnPay: "оплата",
          catalogReply: "витрина, корзина, поиск — всё в чате",
          payReply: "оплата встроена: карты, звёзды, крипта",
          paid: "✓ оплачено",
          reset: "ещё раз",
        },
        web: {
          hint: "наведи — покажу, как собрано",
          labels: ["nav / sticky", "hero / clamp()", "card / --radius", "grid 12"],
        },
      },
    },
    cases: {
      idx: "// 02",
      title: "Работы",
      intro: "Говорить можно что угодно. Вот что мы делали руками:",
      items: [
        {
          id: "novy-uroven",
          tag: "case-01",
          client: "T2 · веб-игра (PWA)",
          title: "Новый уровень",
          text: "Бесконечный климбер для телеком-бренда T2: персонаж-сигнал скачет по вышкам связи сквозь эпохи сетей — от 2G до 6G. Живёт в браузере как PWA: WebGL-рендер, оффлайн-режим, облачный лидерборд.",
          stack: ["React", "TypeScript", "PixiJS · WebGL", "PWA", "Neon"],
          link: "https://novi-uroven.vercel.app",
          linkLabel: "поиграть",
          pageHref: "/work/novy-uroven",
          pageLabel: "подробнее \u2192",
          img: "/cases/novy-uroven.png",
          alt: "Геймплей «Нового уровня»: сигнал прыгает по вышкам связи",
          // лента эпох на постере: прогрессия сетей как мини-история
          strip: [
            {
              img: "/cases/novy-uroven-3g.png",
              cap: "3G",
              alt: "«Новый уровень»: эпоха 3G, низкие вышки над городом",
            },
            {
              img: "/cases/novy-uroven.png",
              cap: "геймплей",
              alt: "Геймплей «Нового уровня»: сигнал прыгает по вышкам связи",
            },
            {
              img: "/cases/novy-uroven-6g.png",
              cap: "6G · финал",
              alt: "«Новый уровень»: эпоха 6G, баннер будущего на орбите",
            },
          ],
        },
        {
          id: "novy-kovcheg",
          tag: "case-02",
          client: "Новый Ковчег · дом торжеств",
          title: "Новый Ковчег",
          text: "Цифровая витрина дома торжеств в Кимовске — целиком. Первый этап живой: четыре зала, три меню и форма брони в тёплом серифном путешествии. Второй — интернет-магазин банкетной доставки — уже в разработке.",
          stack: ["Astro 5", "TypeScript", "GSAP", "Lenis"],
          link: "https://noviykovcheg.ru",
          linkLabel: "на сайт",
          pageHref: "/work/novy-kovcheg",
          pageLabel: "подробнее \u2192",
          img: "/cases/novy-kovcheg.png",
          alt: "Лендинг «Нового Ковчега»: тёмный хиро с люстрой и серифным лого",
          strip: [
            {
              img: "/cases/novy-kovcheg.png",
              cap: "вход",
              alt: "Хиро «Нового Ковчега»: тёмный бархат, люстра, сериф",
            },
            {
              img: "/cases/novy-kovcheg-hall.png",
              cap: "Большой зал",
              alt: "Страница Большого зала с живым фото банкета",
            },
            {
              img: "/cases/novy-kovcheg-menu.png",
              cap: "три меню",
              alt: "Пакеты меню с честной ценой за гостя",
            },
          ],
        },
      ],
      placeholderTitle: "Свободный слот",
      placeholderNote: "Следующим кейсом может стать ваш проект — напишите нам.",
      stampSoon: "скоро",
      closing:
        "Хотите такой же разбор своей задачи — напишите, покажем, что можно сделать.",
    },
    why: {
      idx: "// 03",
      title: "Почему АРИЯ",
      lead: "Большие студии продают процессы: менеджеров, созвоны, отчёты. Мы продаём результат. Нас трое — и каждый отвечает за него лично.",
      bullets: [
        {
          name: "Без испорченного телефона.",
          text: "Вы говорите напрямую с теми, кто проектирует и пишет код.",
        },
        {
          name: "Скорость малой команды.",
          text: "Решения за минуты, первые результаты за дни.",
        },
        {
          name: "Стек 2026 года.",
          text: "Те же инструменты, на которых собраны лучшие продукты, — этот сайт тоже.",
        },
        {
          name: "Worldwide.",
          text: "Любой часовой пояс, русский и английский.",
        },
      ],
    },
    process: {
      idx: "// 04",
      title: "Как пойдёт работа",
      steps: [
        {
          name: "Разговор",
          text: "Созвон или переписка — как удобнее. Разбираем задачу и честно говорим, что взлетит, а что нет.",
        },
        {
          name: "Оценка",
          text: "Честная вилка по деньгам и срокам — быстро и без сюрпризов.",
        },
        {
          name: "Разработка",
          text: "Короткие итерации, демо каждую неделю, никакой тишины на месяц.",
        },
        {
          name: "Запуск — и дальше",
          text: "Публикация, метрики, поддержка. Не исчезаем после релиза.",
        },
      ],
    },
    cta: {
      idx: "// 05",
      title: "Расскажите, что хотите построить",
      sub: "Быстрее всего — Telegram. Опишите задачу в двух предложениях, остальное спросим сами.",
      ticker: "открыты к проектам /// 2026 /// worldwide",
      pricing:
        "Никаких прайсов «от…» — они всё равно врут. Смотрим задачу и называем честную вилку.",
      btnTg: "Написать в Telegram",
      btnMail: "Написать на почту",
      form: {
        hint: "// или соберите бриф прямо здесь — ответим туда, куда удобнее вам",
        name: "Имя",
        contact: "Telegram или почта",
        about: "Что угодно своими словами (необязательно)",
        send: "Отправить",
        sending: "Отправляю…",
        ok: "Получили. Скоро ответим.",
        fail: "Не отправилось. Надёжнее всего — Telegram.",
        off: "Форма проснётся вместе с контактами — пока быстрее в Telegram.",
        what: "что делаем",
        feats: "что внутри",
        stage: "на какой вы стадии",
        products: ["приложение", "tg mini app", "сайт", "бот"],
        features: ["авторизация", "платежи", "админка", "пуши", "ии", "3d"],
        stages: ["только идея", "есть дизайн", "переделать существующее"],
        previewTitle: "новая заявка",
        pProduct: "продукт",
        pFeats: "начинка",
        pStage: "стадия",
        pName: "имя",
        pContact: "контакт",
      },
    },
    footer: {
      brand: "АРИЯ — студия цифровых продуктов",
      rights: "© 2026",
      logLink: "// история версий",
      logHref: "/changelog",
    },
    changelog: {
      title: "История версий",
      lead: "Сайт мы ведём как продукт: релизы, даты, честная история.",
      back: "← на сайт",
      backHref: "/",
      releases: [
        {
          v: "1.6",
          date: "22.08.2026",
          items: [
            "кейс 01 «Новый уровень»: страница в стилистике игры — ночное небо, неон, 3D-диорама вышек",
            "кейс 02 «Новый Ковчег»: бархатный вход, люстра, Призма-хрусталь на цепочке",
            "постеры-ленты на главной, дорожная карта этапов клиента",
            "обвязка лид-формы и цели аналитики — проснутся вместе с доменом",
          ],
        },
        {
          v: "1.5",
          date: "18.08.2026",
          items: [
            "тёмная тема — чернильная ночь: токены, неоновые кнопки, лунный 3D",
            "тумблер в шапке + команда в \u2318K, выбор запоминается",
          ],
        },
        {
          v: "1.4",
          date: "17.08.2026",
          items: [
            "командная палитра ⌘K",
            "Призма переехала на сайт гидом",
            "конструктор брифа с живым превью для телеграма",
            "живые демо в карточках услуг",
            "поле частиц — эхо знака в хиро",
            "живая типографика, приветствия по контексту",
            "морф-переходы страниц, открытые метрики + эта страница",
          ],
        },
        {
          v: "1.3",
          date: "17.08.2026",
          items: [
            "форма → телеграм, SEO, свой 404 с Призмой",
            "Призма получила настоящий 3D и систему эмоций",
          ],
        },
        {
          v: "1.2",
          date: "16.08.2026",
          items: [
            "3D-лого летает зигзагом между сценами",
            "долли-зум-парковка в wordmark футера",
          ],
        },
        {
          v: "1.1",
          date: "16.08.2026",
          items: [
            "прелоадер собирает знак на каждом заходе",
            "свой курсор, бегущие строки, арт секций",
          ],
        },
        {
          v: "1.0",
          date: "15.08.2026",
          items: ["каркас, дизайн-система, RU/EN, тексты"],
        },
      ],
    },
    casePage: {
      back: "\u2190 все работы",
      backHref: "/#work",
      tag: "// case-01",
      client: "T2 \u00b7 веб-игра (PWA)",
      title: "Новый уровень",
      lead: "Веб-игра для мобильного оператора T2 — бесконечный вертикальный климбер. Персонаж-сигнал прыгает по вышкам связи из эпохи 2G в будущее и собирает гигабайты по пути. Открывается по ссылке, а после первого захода работает вовсе без сети — «оператор связи сделал игру, которая работает без связи».",
      play: "поиграть \u2197",
      link: "https://novi-uroven.vercel.app",
      shots: [
        { img: "/cases/novy-uroven-menu.png", cap: "меню — любой кадр узнаваем как T2" },
        { img: "/cases/novy-uroven.png", cap: "геймплей: вышки, провода, новый рекорд" },
        { img: "/cases/novy-uroven-over.png", cap: "проигрыш — «Застряли на 2G. Даже обидно»" },
      ],
      taskH: "Задача",
      taskText: "T2 нужен был ежедневный повод возвращаться: engagement на игровом сегменте, знакомство с продуктовой линейкой через бустеры, названные по реальным услугам, и виральность через лидерборд и шеринг рекордов. Формат — казуальная игра на 3–10 минут в транспорте: без установки и без требований к сети.",
      builtH: "Что внутри",
      built: [
        "Прыжковое ядро на настроенной физике: автопрыжок, one-way платформы, горизонтальный wrap — game feel тюнился на реальных устройствах",
        "Честная процедурная генерация: уровень всегда проходим, игрок умирает только по своей вине — это доказывает валидатор в тестах",
        "Три схемы управления — наклон, свайп, тап-зоны, — чтобы играть даже в трясущейся маршрутке",
        "Эпохи сетей 2G→6G как прогрессия: мир и палитра меняются с высотой",
        "PWA с полным оффлайном: кэш Workbox, прогресс в IndexedDB, мгновенный рестарт",
        "Облачный лидерборд на serverless-Postgres (Neon) + шеринг рекордов",
      ],
      flowH: "Как шла работа",
      flow: [
        { n: "01", name: "Фундамент", text: "Vite + React + TypeScript strict, PixiJS-рендер и автодеплой на Vercel с первого дня." },
        { n: "02", name: "Ядро прыжка", text: "Гравитация, платформы, камера, генерация с пулингом — и цикл тюнинга физики на реальном телефоне." },
        { n: "03", name: "Геймплейная глубина", text: "Бустеры по продуктовой линейке, кристаллы, прогрессия эпох, экономика наград." },
        { n: "04", name: "Итерации", text: "Прод открыт с первого этапа — каждая фича доезжает пушем. Поиграть можно уже сейчас." },
      ],
      erasH: "Эпохи сетей — выше значит быстрее",
      erasNote: "Мир, палитра и баннеры меняются с высотой: 2G → 3G → LTE → 5G → 6G. Кадры сняты прямо из игры:",
      eras: [
        { img: "/cases/novy-uroven-3g.png", cap: "3G · «Уже что-то»" },
        { img: "/cases/novy-uroven-lte.png", cap: "LTE · «Можно ускоряться»" },
        { img: "/cases/novy-uroven-5g.png", cap: "5G · «Почти космос»" },
        { img: "/cases/novy-uroven-6g.png", cap: "6G · «Будущее. Вы в нём первый»" },
      ],
      stackH: "Стек",
      stack: ["React 18", "TypeScript strict", "Vite", "PixiJS 8 \u00b7 WebGL", "Zustand", "PWA \u00b7 Workbox", "IndexedDB", "Neon"],
      ctaH: "Хотите продукт, в который играют?",
      ctaBtn: "обсудить в Telegram",
      strip: {
        cap: "// мир игры: от столба 2G до шпиля 6G",
        hint: "скролл наклоняет · курсор качает · джампер кликается",
        eras: ["2G", "3G", "LTE", "5G", "6G"],
      },
      decor: {
        vign1: "// идея → продукт",
        vign2: "// 4 спринта",
      },
    },
    guide: {
      hello: "привет! я тут живу. тыкни меня — или жми ⌘K",
      services: "всё, что здесь, можно купить — и оно правда работает",
      work: "уже два живых кейса — открывай любой, там всё по-настоящему",
      process: "оценка за 1–2 дня. я слежу за этими тремя",
      contact: "двух предложений хватит — форма летит прямо к нам в телеграм",
      sent: "заявка у нас! команда уже читает. я проверила",
    },
    casePageNk: {
      back: "\u2190 все работы",
      backHref: "/#work",
      tag: "// case-02",
      client: "Новый Ковчег \u00b7 дом торжеств, Кимовск",
      title: "Новый Ковчег",
      lead: "Мы делаем для площадки всё цифровое присутствие целиком. Первый этап \u2014 тёплый серифный лендинг, который продаёт атмосферу четырёх залов и приводит брони владельцу прямо в Telegram. Второй \u2014 интернет-магазин банкетной доставки \u2014 уже в разработке на той же дизайн-системе.",
      play: "на сайт",
      link: "https://noviykovcheg.ru",
      shots: [
        { img: "/cases/novy-kovcheg.png", cap: "вход \u2014 тёмный бархат и люстра" },
        { img: "/cases/novy-kovcheg-hall.png", cap: "Большой зал с живыми фото банкета" },
        { img: "/cases/novy-kovcheg-menu.png", cap: "три меню \u2014 честная цена за гостя" },
      ],
      taskH: "Задача",
      taskText: "У площадки был сайт из другого десятилетия: тяжёлый, только под десктоп, с неактуальными цифрами. Зал выбирают глазами \u2014 значит, сайт должен ощущаться как само место: тёплым, праздничным, точным. И каждая страница должна вести к одному действию \u2014 забронировать дату.",
      builtH: "Что внутри",
      built: [
        "Дизайн-система с нуля: Playfair + Onest, чернила / крем / шампань, фото-рамки с золотой линией",
        "Четыре зала как сцены \u2014 от хрустальных люстр до VIP-комнаты, у каждого свой арт-дирекшн",
        "Три пакета меню с настоящими ценами и отдельной полной страницей меню",
        "Форма брони без тяжёлого бэкенда: заявка летит владельцу в Telegram, фолбэк \u2014 почта",
        "Статика Astro: ноль фреймворк-JS в рантайме, мгновенная загрузка на телефонах гостей",
        "SEO-фундамент: schema EventVenue + FAQ, sitemap, консистентные контакты",
      ],
      flowH: "Как шла работа",
      flow: [
        { n: "01", name: "Мастер-конспект", text: "Цели, структура и поэтапный план с критериями готовности \u2014 согласованы до первого пикселя." },
        { n: "02", name: "Дизайн-система", text: "Палитра, серифная типографика и арт-дирекшн каждой секции \u2014 утверждены письменным брифом." },
        { n: "03", name: "Секции и моушн", text: "Вёрстка с нуля, GSAP-ревилы, Lenis-скролл \u2014 спокойная праздничная хореография." },
        { n: "04", name: "Контент и запуск", text: "Обработка фото, тексты, разметка schema, деплой-пакет под обычный хостинг." },
      ],
      moreH: "Ещё из путешествия",
      more: [
        { img: "/cases/novy-kovcheg-halls.png", cap: "четыре зала на любой масштаб" },
        { img: "/cases/novy-kovcheg-demo.png", cap: "владелец сам показывает все четыре зала" },
        { img: "/cases/novy-kovcheg-form.png", cap: "контакты \u2014 телефоны, Telegram, ВК" },
      ],
      stackH: "Стек",
      stack: ["Astro 5", "TypeScript", "GSAP", "Lenis", "Sharp", "PHP \u2192 Telegram"],
      ctaH: "Хотите сайт, который продаёт атмосферу?",
      ctaBtn: "обсудить в Telegram",
      ch: "глава",
      stagesH: "Дорожная карта",
      stages: [
        {
          st: "этап 01 \u00b7 live",
          live: true,
          name: "Лендинг с бронью",
          text: "Четыре зала, меню, FAQ и лид-форма \u2014 цифровая входная дверь площадки.",
        },
        {
          st: "этап 02 \u00b7 в разработке",
          live: false,
          name: "Интернет-магазин доставки",
          text: "Заказ банкетных блюд онлайн \u2014 та же дизайн-система, единый бренд.",
        },
      ],
    },
    ck: {
      aria: "Командная палитра",
      placeholder: "команда или поиск…",
      empty: "// пусто — попробуй иначе",
      items: [
        { id: "services", label: "Перейти: услуги", hint: "// 01" },
        { id: "work", label: "Перейти: работы", hint: "// 02" },
        { id: "process", label: "Перейти: процесс", hint: "// 04" },
        { id: "contact", label: "Перейти: контакт", hint: "// 05" },
        { id: "lead", label: "Оставить заявку", hint: "форма → телеграм" },
        { id: "lang", label: "Switch to English", hint: "/en" },
        { id: "prisma", label: "Позвать Призму", hint: "маскот" },
        { id: "changelog", label: "История версий", hint: "/changelog" },
        { id: "theme", label: "Переключить тему", hint: "тёмная / светлая" },
      ],
    },
    nf: {
      title: "Кликнули не туда.",
      text: "Такой страницы нет. Призма уже ищет, куда она делась, — а вы пока возвращайтесь на главную.",
      cta: "На главную",
      note: "// prisma ищет эту страницу",
    },
  },
} as const;

export type Dict = (typeof dict)["en"];
